export { default as HeroSection } from './HeroSection';
export { default as VideoSection } from './VideoSection';
export { default as ProblemStatementSection } from './ProblemStatementSection';
export { default as CounterSection } from './CounterSection';
export { default as ProgramsSection } from './ProgramsSection';
export { default as WhyChooseSection } from './WhyChooseSection';
export { default as SocialProofSection } from './SocialProofSection';
export { default as BrochuresSection } from './BrochuresSection';
export { default as FaqSection } from './FaqSection';
